import type { Candidate } from './types';

export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: '1',
    name: 'Olivia Martin',
    email: 'olivia.martin@email.com',
    stage: 'Applied',
    score: 88,
    avatarUrl: 'https://picsum.photos/seed/1/40/40',
    rankingExplanation: 'Strong match on skills and experience, particularly with React and Node.js. Lacks direct experience in the fintech industry but shows strong learning capabilities.',
  },
  {
    id: '2',
    name: 'Jackson Lee',
    email: 'jackson.lee@email.com',
    stage: 'Applied',
    score: 72,
    avatarUrl: 'https://picsum.photos/seed/2/40/40',
    rankingExplanation: 'Good experience in backend development, but primarily with Python/Django. Limited frontend experience which is a key requirement.',
  },
  {
    id: '3',
    name: 'Isabella Nguyen',
    email: 'isabella.nguyen@email.com',
    stage: 'Shortlisted',
    score: 95,
    avatarUrl: 'https://picsum.photos/seed/3/40/40',
    rankingExplanation: 'Exceptional candidate. Perfect match on all required skills, 5+ years in a similar role within the same industry. Highly recommended for interview.',
  },
  {
    id: '4',
    name: 'William Kim',
    email: 'william.kim@email.com',
    stage: 'Shortlisted',
    score: 91,
    avatarUrl: 'https://picsum.photos/seed/4/40/40',
    rankingExplanation: 'Very strong candidate with a background in large-scale data systems. Experience aligns well with the project requirements.',
  },
  {
    id: '5',
    name: 'Sophia Williams',
    email: 'sophia.w@email.com',
    stage: 'Interview',
    score: 93,
    avatarUrl: 'https://picsum.photos/seed/5/40/40',
    rankingExplanation: 'Excellent technical skills and great communication abilities demonstrated in the initial screening. Interview is to assess culture fit.',
  },
  {
    id: '6',
    name: 'Liam Brown',
    email: 'liam.brown@email.com',
    stage: 'Hired',
    score: 98,
    avatarUrl: 'https://picsum.photos/seed/6/40/40',
    rankingExplanation: 'Top-tier candidate. Exceeded all expectations during the interview process. Offer extended and accepted.',
  },
    {
    id: '7',
    name: 'Ava Garcia',
    email: 'ava.g@email.com',
    stage: 'Interview',
    score: 89,
    avatarUrl: 'https://picsum.photos/seed/7/40/40',
    rankingExplanation: 'Strong project management experience. Technical skills are sufficient, interview will focus on leadership capabilities.',
  },
];
